### ISSUE TITLE
Preview Broken without PREVIEW_FRAMERATE in camera.py

### ISSUE THREAD

**Issue by wuwendell** [andreigerashchenko/BWCT-Recorder#2]
Why?? Thought it was being passed in through main. It broke the preview until we remounted the SD card.

Nvm. Wasn't the issue. Still happening

Would restart the pi and connect to WiFi but page would not finish loading. Basically preview just wouldn't load. Until u hit record or mount button. Then sometimes would resolve.

**Comment by andreigerashchenko** [comment]
Behavior is intentional, PREVIEW_FRAMERATE is defined globally and is set to its actual value during initialization
